spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123
logging:
  file:
    name: log/blog-dev.log
  level:
    root: info
    com.edou.blog: debug